name: airship_example
description: Demonstrates how to use the airship plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pull_to_refresh: ^2.0.0
  flutter_section_list: ^1.1.0
  flutter_dotenv: ^5.0.2
  envify: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  envify_generator: ^2.0.2
  build_runner:
  flutter_lints: ^1.0.4
  analyzer:
  airship_flutter:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
